site:
  name: UpBuff
  site: 'https://www.upbuff.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: UpBuff
    template: '%s — UpBuff'
  description: "The ERP Execution Platform Built for SAP & Enterprise ERP"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: UpBuff Technologies
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@upbuff'
    site: '@upbuff'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'blog/category' # Category archive path /blog/category/some-category
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'blog/tag' # Tag archive path /blog/tag/some-tag
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-KN2FLT4WLP"
      partytown: false

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
